---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  attributes:
    java:
      ark_retries: 2
      ark_retry_delay: 10

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    driver:
      box: opscode-ubuntu-14.04
  - name: ubuntu-13.10
    driver:
      box: opscode-ubuntu-13.10
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    driver:
      box: opscode-ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-10.04
    driver:
      box: opscode-ubuntu-10.04
    run_list:
    - recipe[apt]
  - name: debian-6.0.8
    driver:
      box: opscode-debian-6.0.8
    run_list:
    - recipe[apt]
  - name: debian-7.6
    driver:
      box: opscode-debian-7.6
    run_list:
    - recipe[apt]
  - name: debian-7.4
    driver:
      box: opscode-debian-7.4
    run_list:
    - recipe[apt]
  - name: centos-7.0
    driver:
      box: opscode-centos-7.0
  - name: centos-6.5
    driver:
      box: opscode-centos-6.5
  - name: centos-5.10
    driver:
      box: opscode-centos-5.10
  - name: fedora-19
    driver:
      box: opscode-fedora-19
  - name: fedora-20
    driver:
      box: opscode-fedora-20
  - name: macosx-10.10
    driver:
      box: macosx-10.10
    run_list:
    - recipe[homebrew]

suites:
  - name: openjdk
    excludes:
      - fedora-19
      - fedora-20
      - macosx-10.10
    run_list:
      - recipe[java::default]
  - name: openjdk-7
    excludes:
      - ubuntu-10.04
      - debian-6.0.8
      - macosx-10.10
    run_list:
      - recipe[java::default]
    attributes:
      java:
        jdk_version: "7"
  - name: oracle
    excludes:
      - macosx-10.10
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-7
    excludes:
      - macosx-10.10
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
    attributes:
      java:
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-8
    excludes:
      - macosx-10.10
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
    attributes:
      java:
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-direct
    excludes:
      - macosx-10.10
    run_list:
      - recipe[java::oracle]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
  - name: openjdk-direct
    run_list:
      - recipe[java::openjdk]
    excludes:
      - fedora-19
      - fedora-20
      - macosx-10.10
  - name: oracle-rpm
    excludes:
      - macosx-10.10
    run_list:
      - recipe[java]
    attributes:
      java:
        install_flavor: oracle_rpm
        jdk_version: 7
        oracle: 
          accept_oracle_download_terms: true
  - name: homebrew
    excludes:
      - ubuntu-14.04
      - ubuntu-13.10
      - ubuntu-12.04
      - ubuntu-10.04
      - debian-6.0.8
      - debian-7.6
      - debian-7.4
      - centos-7.0
      - centos-6.5
      - centos-5.10
      - fedora-19
      - fedora-20
    run_list:
      - recipe[test_java::default]
      - recipe[java]
    attributes:
      java:
        install_flavor: homebrew
        jdk_version: 8
