---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box
  run_list: ["recipe[apt]"]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.4.4.box
  run_list: ["recipe[apt]"]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-5.9_chef-11.4.4.box

suites:
- name: openjdk
  run_list: ["recipe[minitest-handler]", "recipe[java]"]
  attributes: {}

- name: oracle
  run_list: ["recipe[minitest-handler]", "recipe[java]"]
  attributes:
    java:
      oracle:
        accept_oracle_download_terms: true
      install_flavor: "oracle"
