driver:
  name: vagrant

provisioner:
  name: chef_zero
  attributes:
    java:
      ark_retries: 2
      ark_retry_delay: 10

platforms:
  - name: ubuntu-16.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
suites:
  - name: oracle
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
      # - recipe[test_java::java_cert]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-7
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
      # - recipe[test_java::java_cert]
    attributes:
      java:
        jdk_version: "7"
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-8
    run_list:
      - recipe[test_java::default]
      - recipe[java::default]
      # - recipe[test_java::java_cert]
    attributes:
      java:
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
          jce:
            enabled: true
        install_flavor: oracle
  - name: oracle-direct
    run_list:
      - recipe[java::oracle]
    attributes:
      java:
        oracle:
          accept_oracle_download_terms: true
