---
name: 'macos'
'on':
  pull_request:
  push:
    branches:
      - master
jobs:
    macos:
      runs-on: macos-latest
      steps:
        - name: Check out code
          uses: actions/checkout@master
        - name: Install Chef
          uses: actionshub/chef-install@master
        - name: Run Test Kitchen
          env:
            CHEF_LICENSE: accept-no-persist
            KITCHEN_LOCAL_YAML: kitchen.macos.yml
            TERM: xterm-256color
          run: kitchen test adoptopenjdk-14-macos
          # run: whoami && echo $HOME
